/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moda_tdd_oct2021_LAFORGE;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
